export const payload = {
    title: 'Male-Dominated Micro Enterprises Sectors',
    excerpt: 'Analysis of the top 8 male-dominated micro enterprise sectors in 2017 in Nigeria.',
    body: 'Top 8 Male-Dominated Micro Enterprises Sector, 2017: Real Estates: 100%, Construction: 99.5%, Transport & Storage: 97.5%, Prof. Scientific & Tech Work: 88.1%, Agriculture: 84.9%, Arts, Ent., & Recreation: 77.1%, Admin & Support Serv: 78.7%, Info & Comm: 75% (NBS-SMEDAN)',
    category: 'Business',
    tags: ['Micro Enterprises', 'Gender Disparity', 'Sector Analysis'],
    source: 'NBS-SMEDAN',
    type: 'ng-states',
    query: 'male-dominated micro enterprises sectors',
    icon: 'fa fa-building',
    data: [
      {
        label: 'Lagos',
        value: '100%',
        raw: '100',
        unit: '%',
        percentage: '100',
        content: 'The real estate sector is 100% male-dominated.',
        icon: 'fa fa-home',
      },
      {
        label: 'Oyo',
        value: '100%',
        raw: '100',
        unit: '%',
        percentage: '100',
        content: 'The agricultural sector is 100% male-dominated.',
        icon: 'fa fa-home',
      },
      {
        label: 'Enugu',
        value: '99.5%',
        raw: '99.5',
        unit: '%',
        percentage: '99.5',
        content: 'The construction sector is 99.5% male-dominated.',
        icon: 'fa fa-building',
      },
      {
        label: 'Yobe',
        value: '97.5%',
        raw: '97.5',
        unit: '%',
        percentage: '97.5',
        content: 'The transport and storage sector is 97.5% male-dominated.',
        icon: 'fa fa-truck',
      },
      {
        label: 'Abia',
        value: '88.1%',
        raw: '88.1',
        unit: '%',
        percentage: '88.1',
        content: 'The professional, scientific, and technical work sector is 88.1% male-dominated.',
        icon: 'fa fa-flask',
      },
      {
        label: 'Ogun',
        value: '84.9%',
        raw: '84.9',
        unit: '%',
        percentage: '84.9',
        content: 'The agriculture sector is 84.9% male-dominated.',
        icon: 'fa fa-leaf',
      },
      {
        label: 'Ondo',
        value: '77.1%',
        raw: '77.1',
        unit: '%',
        percentage: '77.1',
        content: 'The arts, entertainment, and recreation sector is 77.1% male-dominated.',
        icon: 'fa fa-theater-masks',
      },
      {
        label: 'Akwa Ibom',
        value: '78.7%',
        raw: '78.7',
        unit: '%',
        percentage: '78.7',
        content: 'The administrative and support services sector is 78.7% male-dominated.',
        icon: 'fa fa-briefcase',
      },
      {
        label: 'Kaduna',
        value: '75%',
        raw: '75',
        unit: '%',
        percentage: '75',
        content: 'The information and communication sector is 75% male-dominated.',
        icon: 'fa fa-laptop',
      },
    ],
    legend: 'The data represents the percentage of males in the top 8 micro enterprise sectors in Nigeria in 2017.',
  };
  